version: '3'

services:

  spring-boot:
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/auction_server?serverTimezone=Asia/Seoul
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: host.docker.internal
#      AWS_SES_ACCESS_KEY:
#      AWS_SES_SECRET_KEY:
#      TEST_API_KEY:
      payment.ret.url: http://host.docker.internal:8080/payments/approve?orderNo=
      payment.ret.cancel.url: http://host.docker.internal:8080/payments/close?orderNo=
      SPRING_ELASTICSEARCH_REST_URIS: http://host.docker.internal:9200  # Elasticsearch 호스트 및 포트 설정
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false

